---
language: node_js
node_js:
  - 8
install:
  - npm install
  - cd frontend && npm install && cd ..
script:
 - npm run build
 - npm run engine.test
 - npm run api.test
 - cd frontend && npm run test && cd ..